spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.model

server:
  port: 8080

logging:
  level:
    com.example: DEBUG